# Generated by Django 5.0.7 on 2024-12-29 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='description',
        ),
    ]
